// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWV68FezSBk7R6beMRBgq0e_9tzJxBUao',
    appId: '1:875770681301:web:8f7060aa03df5e66bdcf5c',
    messagingSenderId: '875770681301',
    projectId: 'ai-diagram-maker',
    authDomain: 'ai-diagram-maker.firebaseapp.com',
    storageBucket: 'ai-diagram-maker.firebasestorage.app',
    measurementId: 'G-KV4CKTVM61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBkgw7PemhRQYnEfLYhT5EdyUuhI06b3M',
    appId: '1:875770681301:android:97c5732915b3362cbdcf5c',
    messagingSenderId: '875770681301',
    projectId: 'ai-diagram-maker',
    storageBucket: 'ai-diagram-maker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXyvEyXwRlXhCBkpT3uPYkYiQd8FCEZ8Y',
    appId: '1:875770681301:ios:c9f860c3da10c44ebdcf5c',
    messagingSenderId: '875770681301',
    projectId: 'ai-diagram-maker',
    storageBucket: 'ai-diagram-maker.firebasestorage.app',
    iosBundleId: 'com.ai.visual.generator.maker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXyvEyXwRlXhCBkpT3uPYkYiQd8FCEZ8Y',
    appId: '1:875770681301:ios:b1eed1804e73a3a6bdcf5c',
    messagingSenderId: '875770681301',
    projectId: 'ai-diagram-maker',
    storageBucket: 'ai-diagram-maker.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWV68FezSBk7R6beMRBgq0e_9tzJxBUao',
    appId: '1:875770681301:web:7b89a7519761f9c6bdcf5c',
    messagingSenderId: '875770681301',
    projectId: 'ai-diagram-maker',
    authDomain: 'ai-diagram-maker.firebaseapp.com',
    storageBucket: 'ai-diagram-maker.firebasestorage.app',
    measurementId: 'G-EN75V9TFE2',
  );

}