// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX5agHcwBfDYBSBs3mxL4DiZ9KsrP0HMI',
    appId: '1:960685646692:web:64bfc6c19ed757cdfbd071',
    messagingSenderId: '960685646692',
    projectId: 'diagram-generator-562d2',
    authDomain: 'diagram-generator-562d2.firebaseapp.com',
    storageBucket: 'diagram-generator-562d2.firebasestorage.app',
    measurementId: 'G-BLMN3N1N26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5qsmqaC4TJ7kUSJRWpKdKGfEkWfgwDeU',
    appId: '1:960685646692:android:7a7ee14da0bc0a4afbd071',
    messagingSenderId: '960685646692',
    projectId: 'diagram-generator-562d2',
    storageBucket: 'diagram-generator-562d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5DWmsk6ZI0EU_p1W0vJViy5n3c3QWevI',
    appId: '1:960685646692:ios:08c718f075254589fbd071',
    messagingSenderId: '960685646692',
    projectId: 'diagram-generator-562d2',
    storageBucket: 'diagram-generator-562d2.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5DWmsk6ZI0EU_p1W0vJViy5n3c3QWevI',
    appId: '1:960685646692:ios:08c718f075254589fbd071',
    messagingSenderId: '960685646692',
    projectId: 'diagram-generator-562d2',
    storageBucket: 'diagram-generator-562d2.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX5agHcwBfDYBSBs3mxL4DiZ9KsrP0HMI',
    appId: '1:960685646692:web:7432c9fd5327e3cafbd071',
    messagingSenderId: '960685646692',
    projectId: 'diagram-generator-562d2',
    authDomain: 'diagram-generator-562d2.firebaseapp.com',
    storageBucket: 'diagram-generator-562d2.firebasestorage.app',
    measurementId: 'G-RRX019FH9Z',
  );
}
