// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC16exf_GXEyXeHtBo6bw6xvIRKTa7U2U',
    appId: '1:453557666577:web:e188ce2556e5e22fe002b0',
    messagingSenderId: '453557666577',
    projectId: 'ai-diagram-generator',
    authDomain: 'ai-diagram-generator.firebaseapp.com',
    storageBucket: 'ai-diagram-generator.firebasestorage.app',
    measurementId: 'G-5ELEJMXVF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmZjiL2T_2I1vKVGaGOEXFKAjkt2M2g-s',
    appId: '1:453557666577:android:731768eb5a8a3976e002b0',
    messagingSenderId: '453557666577',
    projectId: 'ai-diagram-generator',
    storageBucket: 'ai-diagram-generator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaxxWHFvXBPEfbQsUzSqh8VJBq6o2ipKg',
    appId: '1:453557666577:ios:76e4823ec4ebefb0e002b0',
    messagingSenderId: '453557666577',
    projectId: 'ai-diagram-generator',
    storageBucket: 'ai-diagram-generator.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaxxWHFvXBPEfbQsUzSqh8VJBq6o2ipKg',
    appId: '1:453557666577:ios:76e4823ec4ebefb0e002b0',
    messagingSenderId: '453557666577',
    projectId: 'ai-diagram-generator',
    storageBucket: 'ai-diagram-generator.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC16exf_GXEyXeHtBo6bw6xvIRKTa7U2U',
    appId: '1:453557666577:web:2ef6106fbe0bbe3fe002b0',
    messagingSenderId: '453557666577',
    projectId: 'ai-diagram-generator',
    authDomain: 'ai-diagram-generator.firebaseapp.com',
    storageBucket: 'ai-diagram-generator.firebasestorage.app',
    measurementId: 'G-Q96RZV3DVM',
  );

}